name: CD

on:
  push:
    branches:
      - main
      - beta
      - canary

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm test

  publish_canary:
    if: github.ref_name == 'develop'
    uses: ./.github/workflows/publish.yml
    with:
      version_cmd: "version:canary"
      publish_cmd: "publish:canary"

  publish_beta:
    if: github.ref_name == 'beta' && github.event.pull_request.merged == true
    uses: ./.github/workflows/publish.yml
    with:
      version_cmd: "version:beta"
      publish_cmd: "publish:beta"

  publish_stable:
    if: github.ref_name == 'main' && github.event.pull_request.merged == true
    needs: [test]
    uses: ./.github/workflows/publish.yml
    with:
      version_cmd: "version:stable"
      publish_cmd: "publish:stable"
