name: Publish Release

on:
  workflow_call:
    inputs:
      version_cmd:
        required: true
        type: string
      publish_cmd:
        required: true
        type: string

jobs:
  publish_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - run: npm run ${{ inputs.version_cmd }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run ${{ inputs.publish_cmd }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
